shuffle: false
ckpt_path: "model_outputs/gpt2/ckpts"
batch_size: 32
training_args:
  kwargs:
    output_dir: "model_outputs/gpt2/training"
    overwrite_output_dir: True
    num_train_epochs: 5
    per_device_train_batch_size: 10
    save_steps: 100
    save_total_limit: 2
    prediction_loss_only: True
